common: &common
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  pool: 5
user_pass_host: &user_pass_host
  username: root
  password: root
  host: localhost

production: &production
  database: spanineoneone_production
  <<: *common
  <<: *user_pass_host

qa:
  <<: *production
  <<: *user_pass_host

staging:
  <<: *production
  <<: *user_pass_host

development:
  database: spanineoneone_development
  <<: *common
  <<: *user_pass_host


test:
  database: spanineoneone_test
  <<: *common
  <<: *user_pass_host

